### PR TITLE
Add s3 logger configuration

### PR DESCRIPTION
**Pull request by cono**

### CODE REVIEW

**Comment by cono** [comment]
Any news?

**Comment by cono** [comment]
rebased

**Comment by cono** [comment]
@fstehle is it possible to apply my fix?

**Comment by cono** [comment]
@fstehle hey, is it going to be applied? Or should I just fork the repo?

**Comment by seiffert** [comment]
Thanks for your great contribution! We've included your commit in https://github.com/Jimdo/ansible-fastly/pull/48.

**Pull request closed without merging**
